{
 "title": "IOT-dashboard",
 "time": { "from": "2023-12-12T17:52:13.559Z", "to": "2023-12-12T17:52:21.477Z" },
 "panels": [
  {
   "title": "LED",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n    |> range(start: -10mo)\r\n    |> filter(fn: (r) => r._measurement == \"light\")"
    }
   ]
  },
  {
   "title": "Buzz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n    |> range(start: -10mo)\r\n    |> filter(fn: (r) => r._measurement == \"buzz\")"
    }
   ]
  },
  {
   "title": "PIR - Motion detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n    |> range(start: -10mo)\r\n    |> filter(fn: (r) => r._measurement == \"MotionDetection\")"
    }
   ]
  },
  {
   "title": "DHT - Temperature, Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n    |> range(start: -10mo)\r\n    |> filter(fn: (r) => r._measurement == \"Humidity\" or r._measurement == \"Temperature\")"
    }
   ]
  },
  {
   "title": "DUS - Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"iot_bucket\")\r\n    |> range(start: -10mo)\r\n    |> filter(fn: (r) => r._measurement == \"Distance\")"
    }
   ]
  }
 ]
}